CREATE TABLE public.tb_usuario (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	dt_cadastro date NULL,
	email varchar(255) NULL,
	nome varchar(255) NULL,
	perfil int4 NULL,
	senha varchar(255) NULL,
	status bool NOT NULL,
	telefone varchar(255) NULL,
	CONSTRAINT tb_usuario_pkey PRIMARY KEY (id)
);

INSERT INTO tb_usuario 
(nome, email, senha, telefone, perfil, status, dt_cadastro)
VALUES
( 'Rogerio Reis ADS4','rogerio@gmail.com', 'admin','62985914444', '0','true', '2021-04-16'),
( 'Gabriel Cunha ADS4','gabriel@gmail.com', 'admin','62985915555', '0','true', '2021-04-16'),
( 'Aires Ribeiro ADS4','aires@gmail.com', 'admin','62985916666', '0','true', '2021-04-16'),
( 'Lucas França ADS4','lucas@gmail.com', 'admin','62985917777', '0','true', '2021-04-16');


